<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$_store = $_order->getStore();
$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';
$imgUrl =  $_baseImageUrl.$_item->getOrderItem()->getProduct()->getSmallImage();

?>
<tr>
    <td class="product-image" valign="middle">
         <img width="60" height="60" style="border-radius: 5px;" src="<?php echo $imgUrl; ?>" />
    </td>
    <td valign="middle" class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName())." x ".($_item->getQty() * 1); ?></p>
        <!-- <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p> -->
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options" style="padding: 0px; margin: 0px;">
                <?php foreach ($block->getItemOptions() as $option): ?>
                     <dt style="padding: 0px; margin: 0px;"><strong><em><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd style="padding: 0px; margin: 0px;">
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
   <!--  <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td> -->
</tr>
