
<script>
    require(
        [
            'jquery',
            'loader'
        ],function($){
            function fetchData(v){
                $('#loader-faq').show();
                $.get("<?php echo $this->getUrl('easyfaq/index/search'); ?>"+"?query="+v+"&cat="+'<?= $this->getRequest()->getParam('cat') ?>', function(res){
                    var res = JSON.parse(res);
                    $(".faq-container").replaceWith(res.results.replace("/index/search/",""));
                    $(".mp-sidebar.mpcss").replaceWith(res.sidebar);

                    $('#loader-faq').hide();
                }).fail(function() {
                    $('#loader-faq').hide();
                });
            }

            $(".faq-container .filter-toggle").click(function(){
                $('.modal-slide.filter-slide').addClass("_show");
            })
            
            $(document).keydown(function(e) {
              if (e.keyCode == 27) {
                $("input.faq-search").val("");
                fetchData('');
              }
            });

            $('input.faq-search').keyup(function(e){
                if (e.keyCode != 27){
                    fetchData(e.target.value)
                }    
            });
        });
</script>