<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="col-md-12 fcopyright">
	<div class="row">
		<div class="col-md-4 col-sm-6">
			<small class="copyright">
			    <span>&copy; 2020 <span>MobilizeMe</span>. All Rights Reserved.<?php /* @escapeNotVerified */ $block->getCopyright() ?></span>
			</small>
		</div>
		<div class="col-md-4 col-sm-6">
			<a href="<?= $this->getUrl('privacy-policy') ?>"><?= __("Privacy Policy") ?></a>|<a href="<?= $this->getUrl('terms-conditions') ?>"><?= __("Terms & Conditions") ?></a>
		</div>
		<div class="col-md-4 col-sm-12 text-right p-logo">
			<img width="277px" height="33px" src="<?= $block->getViewFileUrl('images/payment-methods.png') ?>"/>
		</div>
	</div>
</div>
