<?php

$slider = $block->createSlider();
$items = $slider->getSlideCollection();
$loader = $this->loaderDimensions($slider->getParams());

$data = $block->getData();

?>

<div class="slider-pro-wrapper">
    <div class="slider-pro-container" style="background-size: #eaeaea; height: <?php echo $loader['height'] ?>px;">
        <div class="loading-mask for-slider">
            <div class="loader">
                <img src="<?php /* @escapeNotVerified */ echo $this->getViewFileUrl("TemplateMonster_FilmSlider::images/loader-2.gif"); ?>"
                    title="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                     alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>">
            </div>
        </div>

        <div id="example1" class="slider-pro <?php echo $loader['position']; ?>">
            <div class="sp-slides owl-carousel">
                <?php foreach($items as $item):?>
                    <?php if($item->getStatus()): ?>
                        <div class="item">
                            <a href="<?= $item->getLink() ? $this->getUrl($item->getLink()) : 'javascript:void(0)' ?>">
                                <picture>
                                  <source media="(min-width:768px)" srcset="<?php echo $block->addUrl($item->getImage()) ?>">
                                  <img src="<?php echo $block->addUrl(strlen($item->getMobileImage()) ? $item->getMobileImage() : $item->getImage()) ?>" alt="<?= $item->getTitle(); ?>" >
                                </picture>
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<script>
    require(['jquery','owlcarousel'],function($){
        var owl = $("#example1 .sp-slides");

        owl.on('initialized.owl.carousel', function(event) {
            $(".slider-pro-container .for-slider").remove();
            $(".slider-pro-container").css({height:'auto'});
        });

        owl.owlCarousel({
            items:1,
            lazyLoad : true,
            dots:true,
            loop:true,
            navText:['<span class="gicon-prev"></span>','<span class="gicon-next"></span>'],
            responsive : {
                0 : {
                    nav:false,
                },
                580 : {
                    nav:false,
                }
            }
        });
    });
</script>