<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php /* @var $block \Amasty\Preorder\Block\Product\View\Preorder\ProductConfigurable */?>
<?php
if (!$block->canShowBlock()) {
    return;
}
?>
<script type="text/javascript">
    require(['jquery', 'Amasty_Preorder/js/product/preorder_configurable'], function($) {
        $widget = $.mage.amastyPreorderConfigurable({
            availabilityElement: '<?= /** @noEscape */ $block->getPreorderNotePosition() ?>',
            isAllProductsPreorder: <?= (int) $block->getIsAllProductsPreorder() ?>,
            preOrderNote: '<?= /** @noEscape */ $block->getPreorderNote() ?>',
            addToCartLabel: '<?= /** @noEscape */ $block->getCartLabel() ?>',
            map: <?= /** @noEscape */ $block->getJsonProductPreorderMap() ?>,
            currentAttributes: <?= /** @noEscape */ $block->getJsonCurrentAttribute() ?>,
            originalNote: '<?= /** @noEscape */ $block->getOriginalNote() ?>'
        });
    });
</script>
