<?php if ($block->isEnabled("product_button")) : ?>
    <div id="payment-request-button" class="payment-request-button action tocart">&nbsp;</div>
    <script>
        require(['jquery', 'cryozonic_stripeexpress'], function(jQuery, stripeexpress) {
            jQuery(document).ready(function() {
                stripeexpress.initStripeExpress('#payment-request-button', '<?php echo $block->getPublishableKey(); ?>', <?php echo \Zend_Json::encode($block->getProductApplePayParams()); ?>, <?php echo \Zend_Json::encode($block->getButtonConfig()); ?>, function (paymentRequestButton, paymentRequest, params, prButton) {
                    stripeexpress.initProductWidget(paymentRequestButton, paymentRequest, params, prButton);
                });
            });
        });
    </script>
<?php endif; ?>
