<?php
	$data = $this->getData();
	$murl = $this->getUrl('pub/media/');
?>
<?php if($data['widget_status'] == 1): ?>
<div class="home-section-3">
	<div class="container">
		<div class="row">
			<?php foreach (range(1, 6) as $i): ?>
				<div class="col-md-2 col-xs-6">
					<?php if(isset($data["b{$i}_image"])): ?>
						<img src="<?= $murl . $data["b{$i}_image"] ?>" alt="<?= $data["b{$i}_title"] ?? null ?>"/>
					<?php endif; ?>
					<small><?= $data["b{$i}_title"] ?? null ?></small>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
</div>
<?php endif; ?>