<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link" id="hd.compare.link" style="display: none;">
    <a class="action compare " title="<?= /* @escapeNotVerified */ __('Compare') ?>"
       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
    >
        <span class="label"><?= /* @escapeNotVerified */ __('Compare') ?></span>
        <span class="counter qty" data-bind="text: parseInt(compareProducts().countCaption)"></span>
    </a>
</li>


<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>}}
</script>
