<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
    $_product = $block->getProduct();

    $images = $block->getGalleryImages()->getItems();
    $mainImage = current(array_filter($images, function ($img) use ($block) {
        return $block->isMainImage($img);
    }));

    if (!empty($images) && empty($mainImage)) {
        $mainImage = $block->getGalleryImages()->getFirstItem();
    }

    $helper = $block->getData('imageHelper');
    $mainImageData = $mainImage ?
        $mainImage->getData('medium_image_url') :
        $helper->getDefaultPlaceholderUrl('image');

    $options = json_decode($block->getGalleryOptions()->getOptionsJson(),true);
    $options['maxheight'] = 710;
    $options['maxwidth'] = 710;
    $options['thumbmargin'] = 10;
    $options['thumbborderwidth'] = 1;

    $_bhelper = $this->helper('TemplateMonster\ShopByBrand\Helper\Data');

    $brand = $_bhelper->getBrandById($_product->getData('brand_id'));

?>
<meta itemprop="mpn" content="<?= $_product->getId() ?>"/>
<meta itemprop="sku" content="<?= $_product->getSku() ?>"/>
<meta itemprop="brand" content="<?= $brand['name'] ?>"/>
<link itemprop="image" href="<?= $mainImageData ?>"/>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ json_encode($options) ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
