<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
    $_product = $block->getProduct();

    $images = $block->getGalleryImages()->getItems();
    $mainImage = current(array_filter($images, function ($img) use ($block) {
        return $block->isMainImage($img);
    }));

    if (!empty($images) && empty($mainImage)) {
        $mainImage = $block->getGalleryImages()->getFirstItem();
    }

    $helper = $block->getData('imageHelper');
    $mainImageData = $mainImage ?
        $mainImage->getData('medium_image_url') :
        $helper->getDefaultPlaceholderUrl('image');

    $options = json_decode($block->getGalleryOptions()->getOptionsJson(),true);
    $options['maxheight'] = 710;
    $options['maxwidth'] = 710;
    $options['thumbmargin'] = 10;
    $options['thumbborderwidth'] = 1;
    // $options['thumbheight'] = 124;
    // $options['thumbwidth'] = 124;

    $_bhelper = $this->helper('TemplateMonster\ShopByBrand\Helper\Data');

    $brand = $_bhelper->getBrandById($_product->getData('brand_id'));

    $images = array_map(function($img){
        if(preg_match("/\.gif$/",$img['thumb'])){
           $img['img'] = preg_replace("/cache(.*?)\w[a-zA-Z0-9]{20,}/i", "", $img['img']);
           $img['full'] = preg_replace("/cache(.*?)\w[a-zA-Z0-9]{20,}/i", "", $img['full']);
        }
        return $img;
    }, json_decode($block->getGalleryImagesJson(), true));

?>
<meta itemprop="mpn" content="<?= $_product->getId() ?>"/>
<meta itemprop="sku" content="<?= $_product->getSku() ?>"/>
<link itemprop="image" href="<?= $mainImageData ?>"/>
<span itemprop="aggregateRating" itemscope itemtype="https://schema.org/AggregateRating">
    <meta itemprop="ratingValue" content="5"/>
  <meta itemprop="ratingCount" content="100"/>
</span>
<meta itemprop="description" content="<?= $_product->getShortDescription() ?>" />
<meta itemprop="brand" content="<?= $brand['name'] ?>"/>


<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="<?= $_product->getName() ?>"
        title="<?= $_product->getName() ?>"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= json_encode($images) ?>,
                "options": <?= /* @noEscape */ json_encode($options) ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
