<div class="product-info-logos">
	<ul>
		<li>
			<img src="<?php echo $this->getViewFileUrl('images/australia-map.png'); ?>"/>
			<span>Australian Owned</span>
		</li>
		<li>
			<img src="<?php echo $this->getViewFileUrl('images/delivery-truck.png'); ?>"/>
			<span>Quick Shipping</span>
		</li>
		<li>
			<img src="<?php echo $this->getViewFileUrl('images/lock.png'); ?>"/>
			<span>Secure Checkout</span>
		</li>
	</ul>
</div>
<?php return; ?>
<!-- <div class="product-payment-logos">
	<ul>
		<li>
			<img src="<?php echo $this->getViewFileUrl('images/afterpay-logo.png'); ?>"/>
		</li>
		<li>
			<img src="<?php echo $this->getViewFileUrl('images/paypal.png'); ?>"/>
		</li>
		<li class="last">
			<img src="<?php echo $this->getViewFileUrl('images/zip-pay.png'); ?>"/>
		</li>
	</ul>
</div> -->