<div class="product-info-logos">
	<ul>
		<li>
			<img alt="Australian Owned" title="Australian Owned" src="<?php echo $this->getViewFileUrl('images/australian-owned-operated.png'); ?>"/>
			<span>Australian Owned</span>
		</li>
		<li>
			<img  alt="Quick Shipping" title="Quick Shipping" src="<?php echo $this->getViewFileUrl('images/local-shipping.png'); ?>"/>
			<span>Quick Shipping</span>
		</li>
		<li>
			<img alt="Secure Checkout" title="Secure Checkout" src="<?php echo $this->getViewFileUrl('images/lock.png'); ?>"/>
			<span>Secure Checkout</span>
		</li>
	</ul>
</div>
<?php return; ?>