<script>
    require(
        [
            'jquery',
            'loader'
        ],function($){

            
            
            function fetchData(v){
                $('#loader-download').show();
                $.get("<?php echo $this->getUrl('downloads/index/search'); ?>"+"?query="+v+"&cat="+'<?= $this->getRequest()->getParam('cat') ?>', function(res){
                    var res = JSON.parse(res);
                    $(".downloads-container").replaceWith(res.results.replace("/index/search/",""));
                    $(".mp-sidebar.mpcss").replaceWith(res.sidebar);
                    $('#loader-download').hide();
                }).fail(function() {
                    $('#loader-download').hide();
                });
            }

            $(".downloads-container .filter-toggle").click(function(){
                $('.modal-slide.filter-slide').addClass("_show");
            })

            $(document).keydown(function(e) {
              if (e.keyCode == 27) {
                $("input.downloads-search").val("");
                fetchData('');
              }
            });

            $('input.downloads-search').keyup(function(e){
                if (e.keyCode != 27){
                    fetchData(e.target.value)
                }
            });
        });
</script>
