<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$_store = $_order->getStore();
$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';
$imgUrl =  $_baseImageUrl.$_item->getProduct()->getSmallImage();


?>

<tr>
    <td class="product-image" valign="middle">
         <img width="60" height="60" style="border-radius: 5px;" src="<?php echo $imgUrl; ?>" />
    </td>
    <td valign="middle" class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
       
        <p class="product-name"><?= $block->escapeHtml($_item->getName())." x ".($_item->getQtyOrdered() * 1); ?></p>
        <!-- <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p> -->
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options" style="padding: 0px; margin: 0px;">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt style="padding: 0px; margin: 0px;"><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd style="padding: 0px; margin: 0px;">
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td valign="middle" class="item-price" style="font-size: 14px; font-weight: 600; color: #666666; line-height: 20px; padding: 0px;">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
