<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \TemplateMonster\FeaturedProduct\Block\FeaturedProduct\Widget\Product\
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if ($exist = ($block->getProductCollections())) {
    $type = 'widget-new-grid';
    $image = 'new_products_content_widget_grid';
    $productCollections = $block->getProductCollections();
    $productItemWidth = $block->getItemWidth();
    $cssClass = $block->getCssClass();

    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $connection = $resource->getConnection();
    $query = $connection->select()->from("catalog_product_entity_text", 'value')->where("`attribute_id` IN (SELECT `attribute_id` FROM `eav_attribute` WHERE `attribute_code` = 'mini_description') AND `entity_id` = :entity_id");

}

?>

<?php if ($exist):?>
    <?php foreach ($productCollections as $primary => $secondaries): ?>
    	<?php if(!empty($secondaries)): ?>
            <?php foreach ($secondaries as $secondary => $products): ?>

                <?php if(count($products) == 0): ?>
                    <div class="not-found"><?php echo __('Products not found.'); ?></div>
                <?php else: ?>
                    <div class="owl-carousel owl-theme <?php echo $cssClass; ?>">
                        <?php foreach ($products as $_item): ?>
                            <div class="item">
                                <div class="product-item-info">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    </a>
                                    <div class="product-item-details">
                                        <?php $catID = max($_item->getCategoryIds()) ?>
                                        <strong class="product-item-name">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                               class="product-item-link">
                                                <?php echo $block->truncateProductName($_item->getName()); ?>

                                                <?php $d = $connection->fetchOne($query, [':entity_id' => $_item->getId()]); ?>

                                                <?php if(!empty($d)){ 
                                                        echo " - ".$d; 
                                                    } 
                                                ?>

                                            </a>
                                        </strong>
                                        <?php echo /* @escapeNotVerified */ $block->getProductPriceHtml($_item, $type); ?>
                                        
                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                <?php endif; ?>

                <?php if(count($productCollections) == 1 && count($secondaries) > 1): ?>
                </div>
                <?php endif; ?>
            <?php endforeach ?>
        <?php else: ?>
            <div class="not-found"><?php /* @escapeNotVerified */ echo __('Products not found.'); ?></div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif;?>
