<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper">
        <img class="<?= /* @escapeNotVerified */ $block->getClass() ?>"
            src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
            title="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"
            alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
