<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_bhelper = $this->helper('TemplateMonster\ShopByBrand\Helper\Data');
?>
<?php
$themeHelper = $this->helper('Magento\Theme\Helper\Theme');
if($themeHelper->isModuleOutputEnabled('TemplateMonster_ThemeOptions')):
    $themeOptionsHelper = $this->helper('TemplateMonster\ThemeOptions\Helper\Data');
    $themeOptions = true;
else:
    $themeOptions = false;
endif;
?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productMetadata = $objectManager->get('Magento\Framework\App\ProductMetadataInterface');
$version = $productMetadata->getVersion();

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$query = $connection->select()->from("catalog_product_entity_text", 'value')->where("`attribute_id` IN (SELECT `attribute_id` FROM `eav_attribute` WHERE `attribute_code` = 'mini_description') AND `entity_id` = :entity_id");
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = $themeOptions ? $themeOptionsHelper->getCategoryShowDesc($viewMode) : false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = $themeOptions ? $themeOptionsHelper->getCategoryShowDesc($viewMode) : false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();

    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?> layout_1"
        data-bind="scope: 'categoryProducts'"
        data-role="category-products">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info <?php if (!$_product->getIsSalable()): ?> product-item-info-hide <?php endif; ?>" data-container="product-grid" itemscope itemtype="https://schema.org/Product" onclick="window.location.href = '<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>'">

                    

                    <?php $_compareUrl = $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($_product); ?>

                    <a role="button" data-id="<?= $_product->getId() ?>" data-post='<?= $_compareUrl ?>' class="product-items-compare-link">
                        <i class="icon-check-empty"></i>
                    </a>

                    <?php
                    if ($version == '2.1.6') {
                        $productImage = $imageBlockBuilder->buildBlock($_product, $image);
                    } else {
                        $productImage = $block->getImage($_product, $image);
                    }
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?php if ($block->getMode() == 'list'): ?>
                    <div class="product-item-photo-wrap">
                    <?php endif; ?>


                    <meta itemprop="mpn" content="<?= $_product->getId() ?>"/>
                    <meta itemprop="sku" content="<?= $_product->getSku() ?>"/>
                    <link itemprop="image" href="<?= $productImage->getUrl() ?>"/>
                    <span itemprop="aggregateRating" itemscope itemtype="https://schema.org/AggregateRating">
                            <meta itemprop="ratingValue" content="5"/>
                          <meta itemprop="ratingCount" content="100"/>
                     </span>
                     <meta itemprop="description" content="<?= $block->escapeHtml($_product->getShortDescription()) ?>" />
                                                           


                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <?php if ($block->getMode() == 'list'): ?>
                        </div>
                    <?php endif; ?>

                    <div class="product details product-item-details">
                        
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name" itemprop="name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <p style="margin: 0">
                            <?php $brand = $_bhelper->getBrandById($_product->getData('brand_id')) ?>
                            <?php if($brand && count($brand)): ?>
                                <meta itemprop="brand" content="<?= $brand['name'] ?>"/>
                                <a class="product-brand-name" href="<?= $this->getUrl($brand['url_key']) ?>"><?= $brand['name'] ?></a>
                            <?php else: ?>
                                <a class="product-brand-name"  href="#">&nbsp;</a>
                            <?php endif; ?>
                        </p>
                        <p class="p-short-desc"><?= $connection->fetchOne($query, [':entity_id' => $_product->getId()]); ?></p>

                        <div class="price-holder">
                            <?php if ($_product->getIsSalable()): ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <?php else: ?>
                                <span class="out-of-stock">Out of Stock</span>
                            <?php endif; ?>
                        </div>


                        <?php #echo $block->getProductDetailsHtml($_product); ?>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<script type="text/x-magento-init">
{"[data-role=category-products]": {"Magento_Ui/js/core/app": {"components":{"categoryProducts":{"component":"Magento_Catalog/js/view/category-compare-products"}}}}}
</script>

<?php endif; ?>
