<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
 <!-- title="<?php #echo $block->getLogoAlt() ?>" -->
<div class="logo" href="<?php echo $block->getUrl(''); ?>" onclick="window.location.href='/'">
    <img src="<?php echo $block->getLogoSrc() ?>" alt="<?php echo $block->getLogoAlt() ?>" title="<?php echo $block->getLogoAlt() ?>" />
</div>