<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php echo $storeName ?>">
    <img src="<?php echo $block->getLogoSrc() ?>"
         alt="<?php echo $block->getLogoAlt() ?>"
         title="<?php echo $block->getLogoAlt() ?>"
         <?php # $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
         <?php # $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />
    <span style="display: none;"><?php echo $block->getLogoAlt() ?></span>
</a>