<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Preorder
 */
?>
<?php
/**
 * @var $block \Amasty\Preorder\Block\Adminhtml\Product\Edit\Action\Attribute\Tab\Inventory\PreOrderJs
 */
?>
<script type="text/javascript">
    require([
            'jquery'
        ],
        function($) {
            var preOrderId = <?= $block->escapeHtml($block->getPreorderId());?>,
                $preorderTab = $("#amasty_preorder_fieldset"),
                inventoryElement = $("#inventory_backorders");
            if (inventoryElement.val() != preOrderId){
                $preorderTab.hide();
            }

            inventoryElement.change(function () {
                if (this.value == preOrderId) {
                    $preorderTab.show();
                } else {
                    $preorderTab.hide();
                }
            });
        }
    );
</script>
