<div id="homebrand" class="home-brand" data-bind="scope:'homebrand'">
<!-- ko template: getTemplate() --><!-- /ko -->
<script type="text/x-magento-init">
{
    "#homebrand": {
        "Magento_Ui/js/core/app": {
           "components": {
                "homebrand": {
                    "component": "TemplateMonster_ShopByBrand/js/home",
                    "template" : "TemplateMonster_ShopByBrand/home"
                    }
                }
            }
        }
}
</script>
</div>